### ISSUE TITLE
I couldn't install

### ISSUE THREAD

**Issue by Ademgenc53** [miqoo1996/google-drive#2]
Hello,
Thank you for sharing.
i downloaded the files not composer
What is .anv file?
How should I specify the package path?
thank you

**Comment by miqoo1996** [comment]
Hello, .env is a config file where you can keep your variables, a key-value storage.
So, if you need to skip/change the part due to some reasons, or for your project needs then you have to make some changes to these lines: [line 11-13](https://github.com/miqoo1996/google-drive/blob/333054a9cb35a9cbe48c5be4832b79c0ac6f4928/src/RepositorIes/GoogleDriveRepository.php#L11)

Thanks

**Comment by Ademgenc53** [comment]
Thank you very much for the reply,
I'm trying to do php coding not commercially, but as a hobby and for myself.
What I want to do is this:
I have a website and I'm backing up automatic database.
I want to make a few options to move this backed up database to a secure
area, FTP to another server, Google Drive service account, and other clouds.
Even backing up your web directory as compressed or uncompressed.
Can I do these with your package?

Thank you again
Best Regards

miqoo1996 ***@***.***>, 4 Eyl 2023 Pzt, 18:19 tarihinde şunu
yazdı:

**Comment by Ademgenc53** [comment]
I am getting the following error on installation
![Ekran görüntüsü 2023-09-06 100711](https://github.com/miqoo1996/google-drive/assets/55327675/0d0cae1b-86e4-450a-9aff-724c1fd713f5)

**Comment by miqoo1996** [comment]
This package is designed only for the Laravel Applications, you cannot install it in other projects.

As I've mentioned earlier, you have to make some code changes, as well as changes to the composer.json file to make the package work in other projects too.

**Comment by Ademgenc53** [comment]
Ok, thank you.

miqoo1996 ***@***.***>, 8 Eyl 2023 Cum, 20:32 tarihinde şunu
yazdı:
